name = "vela-verify-api"
main = "worker.js"
compatibility_date = "2024-11-24"

# 启用 workers.dev 子域（自动路由）
workers_dev = true
preview_urls = true

# KV 绑定
[[kv_namespaces]]
binding = "KV"
id = "6b681f8688364d33b1dbb71fe8c14570"

# 删除所有 [[routes]] 配置